services:
  - type: web
    name: vehicle-service-management
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn vehicleservicemanagement.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: vehicle-service-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.0

databases:
  - name: vehicle-service-db
    databaseName: vehicleservice
    user: vehicleservice
